import { VerticalBox } from "std-widgets.slint";
import { SampleUtils } from "./sample-config.slint";
import { Localization } from "./localization.slint";

export enum ProgressType {
    Initial,
    RenderError,
    RenderStarting,
    Rendering,
    RenderFinished,
    RenderCancelled,
    ProcessorError,
    ProcessorStarting,
    Processing,
    ProcessorFinished,
    ProcessorCancelled
}

export struct ProgressInfo {
    progress-type: ProgressType,
    progress: float,
    error: string,
    // render
    fps: int,
    encoded-duration: duration,
    expected-duration: duration,
    video-size: int,
    eta: duration,
    // process
    source: int,
    current-sample: int,
    total-samples: int
}

export global ProgressUtils {
    pure public function format-duration(d: duration) -> string {
        if (d == -1ms) {
            Localization.tr("formatted-duration-error")
        } else if (d < 0s) {
            Localization.tr("formatted-duration-unknown")
        } else {
            Localization.tr-args("formatted-duration", [
                Localization.arg("hours", Math.floor(d / 3600s)),
                Localization.arg("minutes", Math.floor(Math.mod(d / 60s, 60))),
                Localization.arg("seconds", Math.floor(Math.mod(d / 1s, 60)))
            ])
        }
    }

    pure public function humanize-duration(d: duration) -> string {
        if (d < 0s) {
            Localization.tr("remaining-duration-unknown")
        } else if (d / 3600s >= 1) {
            Localization.tr-args("remaining-duration-hours", [
                Localization.int-arg("n", Math.floor(d / 3600s))
            ])
        } else if (d / 60s >= 1) {
            Localization.tr-args("remaining-duration-minutes", [
                Localization.int-arg("n", Math.floor(d / 60s))
            ])
        } else if (d / 1s >= 1) {
            Localization.tr-args("remaining-duration-seconds", [
                Localization.int-arg("n", Math.floor(d / 1s))
            ])
        } else {
            Localization.tr("remaining-duration-less-than-a-second")
        }
    }

    pure public function humanize-size(b: int) -> string {
        if (b >= 1073741824) {
            Localization.tr-args("file-size-gibibytes", [
                Localization.arg("n", Math.round(b / 10737418.24) / 100)
            ])
        } else if (b >= 1048576) {
            Localization.tr-args("file-size-mebibytes", [
                Localization.arg("n", Math.round(b / 10485.76) / 100)
            ])
        } else if (b >= 1024) {
            Localization.tr-args("file-size-kibibytes", [
                Localization.arg("n", Math.round(b / 10.24) / 100)
            ])
        } else {
            Localization.tr-args("file-size-bytes", [
                Localization.int-arg("n", b)
            ])
        }
    }
}

export component Progress {
    in property <ProgressInfo> progress-info;

    property<float> i-progress-anim-tick: -cos(180deg * mod(animation-tick() / 1.3s, 2) / 2) + 1;

    pure function progress-title() -> string {
        if (root.progress-info.progress-type == ProgressType.RenderStarting || root.progress-info.progress-type == ProgressType.ProcessorStarting) {
            Localization.tr("progress-title-starting")
        } else if (root.progress-info.progress-type == ProgressType.Rendering) {
            if (root.progress-info.expected-duration >= 0s) {
                Localization.tr("progress-title-rendering")
            } else if (root.progress-info.encoded-duration >= 0s) {
                Localization.tr("progress-title-rendering-to-loop-point")
            } else {
                Localization.tr("progress-title-rendering-initializing")
            }
        } else if (root.progress-info.progress-type == ProgressType.Processing) {
            if (root.progress-info.current-sample == 0) {
                Localization.tr("progress-title-processing-detecting-samples")
            } else {
                Localization.tr("progress-title-processing-processing-samples")
            }
        } else {
            Localization.tr("progress-title-idle")
        }
    }

    pure function progress-status() -> string {
        if (root.progress-info.progress-type == ProgressType.RenderError) {
            Localization.tr-args("progress-status-render-error", [
                Localization.arg("error", root.progress-info.error)
            ])
        } else if (root.progress-info.progress-type == ProgressType.RenderStarting) {
            Localization.tr("progress-status-render-starting")
        } else if (root.progress-info.progress-type == ProgressType.Rendering) {
            Localization.tr-args("progress-status-rendering", [
                Localization.arg("progress", root.progress-info.progress),
                Localization.int-arg("fps", root.progress-info.fps),
                Localization.arg("encodedDuration", ProgressUtils.format-duration(root.progress-info.encoded-duration)),
                Localization.arg("expectedDuration", ProgressUtils.format-duration(root.progress-info.expected-duration)),
                Localization.arg("videoSize", ProgressUtils.humanize-size(root.progress-info.video-size)),
                Localization.arg("eta", ProgressUtils.humanize-duration(root.progress-info.eta)),
            ])
        } else if (root.progress-info.progress-type == ProgressType.RenderFinished) {
            Localization.tr("progress-status-render-finished")
        } else if (root.progress-info.progress-type == ProgressType.RenderCancelled) {
            Localization.tr("progress-status-render-cancelled")
        } else if (root.progress-info.progress-type == ProgressType.ProcessorError) {
            Localization.tr-args("progress-status-processor-error", [
                Localization.arg("error", root.progress-info.error)
            ])
        } else if (root.progress-info.progress-type == ProgressType.ProcessorStarting) {
            Localization.tr("progress-status-processor-starting")
        } else if (root.progress-info.progress-type == ProgressType.Processing && root.progress-info.current-sample == 0) {
            Localization.tr-args("progress-status-processing-detecting-samples", [
                Localization.arg("progress", root.progress-info.progress),
                Localization.int-arg("detectedSamples", root.progress-info.total-samples)
            ])
        } else if (root.progress-info.progress-type == ProgressType.Processing && root.progress-info.current-sample != 0) {
            Localization.tr-args("progress-status-processing-processing-samples", [
                Localization.arg("progress", root.progress-info.progress),
                Localization.arg("sourceIndex", SampleUtils.format-hex(root.progress-info.source)),
                Localization.int-arg("currentSample", root.progress-info.current-sample),
                Localization.int-arg("totalSamples", root.progress-info.total-samples)
            ])
        } else if (root.progress-info.progress-type == ProgressType.ProcessorFinished) {
            Localization.tr("progress-status-processor-finished")
        } else if (root.progress-info.progress-type == ProgressType.ProcessorCancelled) {
            Localization.tr("progress-status-processor-cancelled")
        } else {
            ""
        }
    }

    pure function progress-indeterminate() -> bool {
        root.progress-info.progress-type == ProgressType.RenderStarting || root.progress-info.progress-type == ProgressType.ProcessorStarting || (root.progress-info.progress-type == ProgressType.Rendering && root.progress-info.expected-duration <= 0s)
    }

    pure function progress-error() -> bool {
        root.progress-info.progress-type == ProgressType.RenderError || root.progress-info.progress-type == ProgressType.ProcessorError
    }

    VerticalBox {
        alignment: start;
        spacing: 8px;

        Text {
            text: root.progress-title();
            font-size: 16px;
        }
        Rectangle {
            height: 6px;
            clip: true;

            border-radius: 3px;
            background: #FFFFFF14;

            if !root.progress-indeterminate(): Rectangle {
                x: 0;
                y: 0;
                height: parent.height;
                width: Math.max(0.0, Math.min(root.progress-info.progress, 1.0)) * parent.width;

                border-width: 1px;
                border-radius: 3px;
                border-color: root.progress-error() ? #bc2f32 : #60cdff;
                background: root.progress-error() ? #bc2f32 : #60cdff;

                animate width {
                    duration: 100ms;
                    easing: ease-in-out;
                }
            }
            if root.progress-indeterminate(): Rectangle {
                x: (4 * (root.i-progress-anim-tick / 1.4) - 1) * parent.width;
                y: 0;
                height: parent.height;
                width: 0.5 * parent.width;

                border-width: 1px;
                border-radius: 3px;
                border-color: root.i-progress-anim-tick > 1.4 ? transparent : #60cdff;
                background: root.i-progress-anim-tick > 1.4 ? transparent : #60cdff;
            }
            if root.progress-indeterminate(): Rectangle {
                x: (3.1666 * ((root.i-progress-anim-tick - 0.6) / 1.4) - 1.5) * parent.width;
                y: 0;
                height: parent.height;
                width: 0.8 * parent.width;

                border-width: 1px;
                border-radius: 3px;
                border-color: root.i-progress-anim-tick < 0.6 ? transparent : #60cdff;
                background: root.i-progress-anim-tick < 0.6 ? transparent : #60cdff;
            }
        }
        HorizontalLayout {
            alignment: start;
            spacing: 6px;

            if root.progress-error(): Image {
                colorize: #bc2f32;
                height: 16px;
                width: 16px;
                source: @image-url("circle-error.svg");
            }
            Text {
                text: root.progress-status();
                color: root.progress-error() ? #bc2f32 : #ffffff;
                vertical-alignment: center;
            }
        }
    }
}
